
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02a_why_sqrt5.ipynb

from exp.nb_02 import *